
OrdererOrgs:
  
  - Name: Orderer
    Domain: csr.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:

  - Name: Corporate
    Domain: corporate.csr.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
 
  - Name: CreditsAuthority
    Domain: creditsauthority.csr.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Ngo
    Domain: ngo.csr.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  # - Name: ItDepartment
  #   Domain: itdepartment.csr.com
  #   EnableNodeOUs: true
  #   Template:
  #     Count: 2
  #   Users:
  #     Count: 1

  # - Name: Citizen
  #   Domain: citizen.csr.com
  #   EnableNodeOUs: true
  #   Template:
  #     Count: 2
  #   Users:
  #     Count: 1